### ISSUE TITLE
Script Crashes with METAR Dew Point?

### ISSUE THREAD

**Issue by jmlaforest** [evogelsa/DCS-real-weather#1]
I noticed that if I pull METAR from a location putting the dewpoint below zero in with the humidity (i.e. 30/M02) I get teh following error

![image](https://user-images.githubusercontent.com/73452559/117906085-dcdacf80-b299-11eb-8739-798d4ff02a41.png)

Compared the following METARS and the KICT and KSAN did not have this issue but KTPH and KLAS do.

**KTPH 120056Z AUTO 31014KT 10SM CLR 23/M17 A3006 RMK AO2 SLP132 T02281172
KLAS 120056Z 36003KT 10SM CLR 30/M09 A2988 RMK AO2 SLP096 T03001089**
KICT 120053Z 06009KT 10SM FEW045 BKN080 14/05 A3023 RMK AO2 SLP234 T01390050
KSAN 120051Z 23007KT 180V250 10SM SCT020 19/12 A2994 RMK AO2 SLP137 T01890117

**Comment by evogelsa** [comment]
I just posted a new release (v1.3.1). I don't think it will fix the issue, but could you try it again with that version and post the screenshot? Also what version are you running here?

**Comment by jmlaforest** [comment]
![image](https://user-images.githubusercontent.com/73452559/117917289-61374d80-b2ae-11eb-8270-6d813245cf6d.png)
This is with v1.3.1
Confirmed weather preset was set on the mission.

Good catch on the CLR, I missed that one after I noticed the M Dew Point.

**Comment by evogelsa** [comment]
What ICAO are you using here?

**Comment by jmlaforest** [comment]
KTPH, I've also had it with KLAS and in the past tonight.

**Comment by evogelsa** [comment]
Think I found the issue, try latest release.

**Comment by jmlaforest** [comment]
worked, thank you

**Comment by evogelsa** [comment]
Great, thanks for finding this bug!
