### ISSUE TITLE
Manage the preset no cloud for avoid corrupted mission

### ISSUE THREAD

**Issue by Phil8811** [evogelsa/DCS-real-weather#11]
Hi Please fix realweather corrupting missions when no preset is set. If you don't know how to apply a dummy preset, then maybe just exit with an error instead of writing a damaged mission file.

In DCSbot no preset is managed like this:
```
        "No Cloud": {
          "clouds": ""
        },

```
Best regards

**Comment by evogelsa** [comment]
Implemented in c6885e2 and published in release v1.7.0.

**Comment by Phil8811** [comment]
Great :-)))
