### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Phil8811** [evogelsa/DCS-real-weather#12]
If you could you add the version number to the exe should great too

Best regards

**Comment by evogelsa** [comment]
The executable files are intentionally all named the same to make drop in replacements easy for server owners. Feel free to rename the .exe yourself though if you would prefer that. The .zip directories are named for this reason :-)

**Comment by Phil8811** [comment]
I mean Product Version
![image](https://github.com/evogelsa/DCS-real-weather/assets/23659925/5e4bc4b5-bcde-43ca-aaa5-0183eb0d5a67)

Best regards

**Comment by evogelsa** [comment]
Ah I see. I will look into it as a low priority improvement!
