### ISSUE TITLE
Realweather reincapsulating wrong miz file

### ISSUE THREAD

**Issue by jojom4n** [evogelsa/DCS-real-weather#2]
I used realweather but it badly modified the "mission" file inside the .miz file.

More precisely, realweather did not include the following statement in the weather section of the mission file, so mission could not be opened or run:

}, -- end of ["clouds"]

**Comment by evogelsa** [comment]
Hm. Can't be sure without testing it, but this sounds like something that would happen if a cloud preset isn't selected in the mission file you're trying to update. Can you try again and make sure that you have cloud preset selected (doesn't matter which one as long as it isn't clear skies).

If this isn't the problem I'll have to dig into it tonight.

**Comment by jojom4n** [comment]
Yes, that appeared to be the problem, thanks! 

But now I'm doubtful about the following: after your feedback, my "original" mission has (now) a light scattered cloud preset and Realweather (now) worked successfully and updated METAR (I'm using URSS airbase, i.e. Sochi).

In the "new" mission (i.e. the one packed by Realweather) there isn't any more cloud preset though. 

This brings me to think that, should I run Realweather again on the "new" mission in a few hours, will the mission be corrupted since on its first run Realweather removed the cloud preset, right?

**Comment by evogelsa** [comment]
I'm not sure if I'm understanding the question right but here's how my group's workflow typically works:

We have one "base mission file" that has all our assets and default settings with random cloud preset selected. Our server restarts every 4 hours and during this restart cycle it updates the base mission file and outputs a new "real weather mission file."

That real weather mission file gets copied over to the server directory and used for the next 4 hours. When the server comes down for restart, it updates the base mission file again and we get a new real weather mission file. There's an example script to do something similar to this in the [examples folder](https://github.com/evogelsa/DCS-real-weather/blob/master/examples/starting_scripts/start_all_rw.bat).

Honestly, I'm not sure if I've tried updating using the real weather mission file before. I think it should work, but it should also be easy enough for you to try out too.

**Comment by evogelsa** [comment]
> EDIT: after examining better the mission that Realweather processed, it seems to me that weather was not correctly set. I tried to use some different airbases, but the mission, processed by Realweather, always reverts to the worst possible weather conditions (cloud base and thickness to minimum, no cloud preset).

Could be possible that the lua format has changed since I last updated this utility. If you can open a new issue with more details I can help diagnose.
