### ISSUE TITLE
Turbulence parameter should get populated

### ISSUE THREAD

**Issue by hawaiianryan808** [evogelsa/dcs-real-weather#29]
It seems that the turbulence parameter of the winds is always zero. Can it be a function of at least the ground-level wind speed?

**Comment by evogelsa** [comment]
Ground turbulence is already dependent on wind speed at ground level. It is set directly from the `wind.gust_mps` parameter from the CheckWx response. You may be seeing values of zero often if the airport you are using does not regularly have gusting conditions.
