### ISSUE TITLE
RW does not seem to work anymore

### ISSUE THREAD

**Issue by jojom4n** [evogelsa/DCS-real-weather#3]
I had been successfully using RW in the past. Today, after some time I've not been updating any mission, I tried to update some missions of mine and noticed RW does not update them.

More precisely, every mission, after being processed by RW, has no cloud preset and has cloud base, thickness and density to minimum values. Wind is instead correctly updated.

I'm attaching a zip contaning: 
a) one of the many "original" mission files I tried RW with (mission.miz); 
b) the resulting miz file after being processed by RW (realweather.zip); 
c) RW logfile (logfile.log); 
d) my config.json (of course, I'm going to remove the API key and replace it with a series of 'x' for safety reason).

Thank
[RW issue.zip](https://github.com/evogelsa/DCS-real-weather/files/7488688/RW.issue.zip)
s.

**Comment by evogelsa** [comment]
Thanks for making a new issue. I'm looking at your logfile, and I'm unsure if this is actually a bug.

Here's the METAR that the utility is receiving from checkwx:
`URSS 052000Z 04005MPS 9999 NSC 15/09 Q1022 R02/010070 R06/010070 NOSIG RMK R06/00000MPS QFE765`

And the METAR the utility is generating after translating to closest DCS match:
`URSS 052000Z 04010KT 6SM CLR 15/09 A3018 NOSIG`

Basically the METAR you're getting says there are clear skies so the realweather utility is replicating that. You can confirm this by using an ICAO that has some weather other than clear skies and ensure that the weather is updated accordingly.

**Comment by jojom4n** [comment]
I'll try other airbases, with not so clear skies, and let you know. Thanks for feedback.

**Comment by jojom4n** [comment]
RW rightly updated the miz file with a METAR with broken clouds and rain. Closing issue, thx.
