### ISSUE TITLE
runway-elevation cannot be float

### ISSUE THREAD

**Issue by hawaiianryan808** [evogelsa/dcs-real-weather#30]
Seems that the runway-elevation parameter in config.json _must_ be an integer. The program should probably accept a float without throwing an error.

**Comment by evogelsa** [comment]
This is as designed. The runway elevation parameter is expected to be an integer value. However, I can update the config validation to accept floating values and cast them to integers rather than erroring out.

**Comment by evogelsa** [comment]
After further review, I've decided this will not be implemented. Currently I don't believe allowing decimal values for the integer parameters will add much value. The expected types of the parameters are documented in the [config parameters](https://github.com/evogelsa/dcs-real-weather?tab=readme-ov-file#config-parameters) section of the README. If you disagree, please comment with the feature request issue template and provide some rationale.

**Comment by evogelsa** [comment]
FWIW the configuration overhaul as over [v2.0.0-beta-1](https://github.com/evogelsa/dcs-real-weather/releases/tag/v2.0.0-beta-1) should now allow any number for runway elevation.
